### PR TITLE
Use upstream OpenFST

### PR DESCRIPTION
**Pull request by AmbientLighter**
Fixes issue https://github.com/hfst/hfst/issues/484

### CODE REVIEW

**Comment by TinoDidriksen** [comment]
As the issue mentions, we don't want to delete the bundled code until HFST has been fully battle-tested when linked against external. It should be a configure flag at first

**Comment by AmbientLighter** [comment]
@TinoDidriksen Okay, I've updated PR to fix this.

**Comment by AmbientLighter** [comment]
@TinoDidriksen pull request is ready for review

**Comment by TinoDidriksen** [comment]
I've seen it - I just need to test it first, which I'll probably do later tonight.

**Comment by TinoDidriksen** [comment]
Merged as https://github.com/hfst/hfst/commit/734ae775580f36ad2bf798a96428c121014f2208 with some minor additions.

**Pull request closed without merging**
